import React, { useState } from 'react';
import {FormField, Loader} from '../component'

const RenderCard = ({data, title}) => {
  if(data?.length > 0){
    return data.map((post) => <Card key={post._id}{...post}/>)
  }
  else
  return(
    <h2
    className='font-bold mt-1 text-lg uppercase'>
      {title}
    </h2>
  )
}
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null)
  const [searchText, setSearchText] = useState("images")

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='mt-1 font-extrabold'>
          The Community Showcase
          </h1>
          <p>
            Browse through a collection of visually stunning images
            generated by DALLE AI 3.0
          </p>
      </div>
      <div className='mt-16'>
        <FormField/>
      </div>
      <div
      className='mt-5'>
        {loading ? (<div className='flex justify-center items-center'>
        <Loader/>
        </div>
        ) : (
          <>
          {searchText && (
            <h2>Showing results for <span className='text-[#6469ff] italic font-bold'>{searchText}</span></h2>
          )}
          <div
          className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
          {searchText ? (
            <RenderCard
            data = {[]}
            title = "No search results found"
            />
          ): (
            <RenderCard
            data= {[]}
            title= "No posts found"/>
          )}
          </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home